FORMAT: 1A

# Odbav.to

## Translations for one exact locale [/translations]
### List of translated texts [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `SOME_KEY`: `some text to replace` (string, required)
        + `ANOTHER_KEY`: `some text to replace` (string, required)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Translations [/translations/list]
### List of translated texts [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `en` (object)
            + `SOME_KEY`: `some text to replace` (string, required)
            + `ANOTHER_KEY`: `some text to replace` (string, required)
        + `cs` (object)
            + `SOME_KEY`: `some text to replace` (string, required)
            + `ANOTHER_KEY`: `some text to replace` (string, required)

+ Response 401 (application/json)
    + Attributes (401 Error response)


## Licence types [/licence-types]
### List of all licence types [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Licence type with details)

## Currencies [/currencies]
### List of supported currencies [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Currency)

## Countries [/countries]
### List of supported countries [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Country)
            + `currency`: `CZK`

## Logged user [/me]
### Retrieve informations about itself [GET]
+ Request (application/json)
        
+ Response 200 (application/json)
    + Attributes (User with customer)

+ Response 401 (application/json)
    + Attributes (401 Error response)


### Update user details [PUT]
+ Request (application/json)
    + Attributes (User without email)
        + `skipTutorial`: true (boolean)
            
+ Response 200 (application/json)
    + Attributes (User with customer)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Check in [/check-in]
### Check code for check in [POST]
+ Request (application/json)
    + Attributes (object)
        + `code`: `c084806e45e5` (string, required)

+ Response 201 (application/json)
    + Attributes (Ticket detail)

+ Response 400 (application/json)
    + Attributes
        + `ticket` (Ticket detail)
        + Include 400 Error response

+ Response 401 (application/json)
    + Attributes (401 Error response)


## Check out [/check-out]
### Check code for check out [POST]
+ Request (application/json)
    + Attributes (object)
        + `code`: `c084806e45e5` (string, required)

+ Response 201 (application/json)
    + Attributes (Ticket detail)

+ Response 400 (application/json)
    + Attributes
        + `ticket` (Ticket detail)
        + Include 400 Error response

+ Response 401 (application/json)
    + Attributes (401 Error response)


## Events [/events]
### List events [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Event with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)

### Create new event [POST]
+ Request (application/json)
    + Attributes (Event)

+ Response 201 (application/json)
    + Attributes (Event with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Cancel event [/events/cancel]
### Cancel event [POST]
+ Request (application/json)
    + Attributes (object)
        + `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Event detail [/events/{eventId}]
### Event detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Event with id and variants)
        
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit event details [PUT]
+ Request (application/json)
    + Attributes (Event body)

+ Response 200 (application/json)
    + Attributes (Event with id)
        
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## SubEvents [/events/{eventId}/sub-events]
### Create new subEvent [POST]
+ Request (application/json)
    + Attributes (SubEvent body)

+ Response 201 (application/json)
    + Attributes (Event with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Terms and conditions for Event [/events/{eventId}/terms-and-conditions]
### Terms detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Event terms)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit Terms [PUT]
+ Request (application/json)
    + Attributes (Event terms)

+ Response 200 (application/json)
    + Attributes (Event terms)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 404 (application/json)
    + Attributes (404 Error response)

## Ticket variants [/events/{eventId}/ticket-variants]
### List event ticket variants [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Single ticket variant detail)
        + (Group ticket variant detail)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create new ticket variant [POST]
+ Request Single ticket variant (application/json)
    + Attributes (Single ticket variant body)

+ Response 201 (application/json)
    + Attributes (Single ticket variant detail)

+ Request Group ticket variant (application/json)
    + Attributes (Group ticket variant body)

+ Response 201 (application/json)
    + Attributes (Group ticket variant detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel ticket variant [/ticket-variants/cancel]
### Cancel ticket variant [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketVariantId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Ticket variant detail [/ticket-variants/{ticketVariantId}]
### Ticket variant detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Single ticket variant detail)

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Group ticket variant detail)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit ticket variant [PUT]
+ Request Single ticket variant (application/json)
    + Attributes (Single ticket variant body)

+ Response 200 (application/json)
    + Attributes (Single ticket variant detail)

+ Request Group ticket variant (application/json)
    + Attributes (Group ticket variant body)

+ Response 200 (application/json)
    + Attributes (Group ticket variant detail)
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Tickets [/events/{eventId}/tickets]
### List event tickets [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Ticket response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create new ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `variantId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`
        + `guest` (Guest)

+ Response 201 (application/json)
    + Attributes (Ticket detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel ticket [/tickets/cancel]
### Cancel ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Ticket detail [/tickets/{ticketId}]
### Ticket detail [GET]
+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (Ticket detail)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit ticket [PUT]
+ Request (application/json)
    + Attributes (Ticket editation)
        
+ Response 200 (application/json)
    + Attributes (Ticket detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Ticket downloading [/tickets/{ticketId}/download]
### Download ticket [GET]
+ Request (application/json)

+ Response 200 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Tickets sending [/tickets/send]
### Send ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketId` (string, required)
        + `email` (string, required) - Email to which deliver the ticket

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Orders [/orders]
### List orders [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Order response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create order (customer from outside) [POST]
+ Request (application/json)
    + Attributes (Order request)
        + `tickets` (Order ticket)
        + `groupTickets` (Order Group ticket)
        
+ Response 201 (application/json)
    + Attributes (Order detail)
        
+ Request Custom inputs (application/json)
    + Attributes (Order request)
        + `tickets` (array[object])
            + (Order ticket detailed)
                + `inputs` (array[Custom input request])
        + `groupTickets` (array[object])
            + (Order Group ticket detailed)
                + `inputs` (array[Custom input request])
        
+ Response 201 (application/json)
    + Attributes (Order detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)

### Delete order [DELETE]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string)
        
+ Response 204 (application/json)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Event orders [/events/{eventId}/orders]
### List event orders [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Order detail)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

### Create order (manual or cashdesk) [POST]
+ Request (application/json)
    + Attributes (Order request)
        + `tickets` (Order ticket)

+ Response 201 (application/json)
    + Attributes (Order detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (400 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel order [/orders/cancel]
### Cancel order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string)

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Facebook [/events/{eventId}/facebook-connections]
### List of event facebook connections [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (object)
            + `pageId`: `395697660571849` (string)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Connect event to a facebook page [POST]
+ Request (application/json)
    + Attributes (array)
        + (object)
            + `pageId`: `395697660571849` (string, required)

+ Response 204 (application/json)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Delete facebook connection [DELETE]
+ Request (application/json)
    + Attributes (object)
        + `pageId` (string, required)

+ Response 204 (application/json)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Invoices sending [/orders/send-invoice]
### Send invoice for order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string, required)
        + `email` (string, required) - Email to which deliver the invoice

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Order tickets sending [/orders/send-tickets]
### Send all tickets belonging to order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string, required)
        + `email` (string, required) - Email to which deliver the tickets

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Mark order as paid [/orders/mark-as-paid]
### Mark order as paid [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string, required)

+ Response 200 (application/json)
    + Attributes (Order detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Order detail [/orders/{orderId}]
### Order detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Order detail)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit order [PUT]
+ Request (application/json)
    + Attributes (Order request)

+ Response 200 (application/json)
    + Attributes (Order detail)
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Order's invoice downloading [/orders/{orderId}/download-invoice]
### Download order invoice [GET]
+ Request (application/json)

+ Response 200 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Order's tickets downloading [/orders/{orderId}/download-tickets]
### Download order tickets [GET]
+ Request (application/json)

+ Response 200 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Pay order [/orders/{orderId}/payment-gateway]
### Create transaction and redirect [POST]
+ Request (application/json)
    + Attributes
        + `successReturnUrl`: `http://odbav.to/some-success-url` (string, required) - Url where user will be returned on successful payment
        + `failureReturnUrl`: `http://odbav.to/some-failure-url` (string, required) - Url where user will be returned on failed payment

+ Response 302 (application/json)

+ Response 400 (application/json)
    + Attributes (400 Error response)

## Company info [/company-info/{companyId}]
### Retrieve info from public registry [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Company)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Billing detail [/billing]
### Billing detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Billing info)
        + `customerId`: `5f470e02-3442-488a-9c2c-804e16520e44`

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit billing [PUT]
+ Request (application/json)
    + Attributes (Billing info)

+ Response 200 (application/json)
    + Attributes (Billing info)
        + `customerId`: `5f470e02-3442-488a-9c2c-804e16520e44`
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Discounts of event [/events/{eventId}/discounts]
### List of discounts [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Discount response])

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Add discount [POST]
+ Request (application/json)
    + Attributes (Discount request)

+ Response 200 (application/json)
    + Attributes (Discount response)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Discount by code [/events/{eventId}/discounts/{discountCode}]
### Discount of code [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Discount response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Discount [/discounts/{discountId}]
### Discount detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Discount response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit discount [PUT]
+ Request (application/json)
    + Attributes (Discount request)

+ Response 200 (application/json)
    + Attributes (Discount response)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)    

## Cancel discount [/discounts/cancel]
### Cancel discount [POST]
+ Request (application/json)
    + Attributes
        + `discountId` (string, required)

+ Response 200 (application/json)
    + Attributes (Discount response)
    
+ Response 400 (application/json)
    + Attributes (401 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Ticket inputs of event [/events/{eventId}/ticket-inputs]
### List of inputs [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Ticket input response])

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Add ticket input [POST]
+ Request (application/json)
    + Attributes (Ticket input request)

+ Response 200 (application/json)
    + Attributes (Ticket input response)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Event analytics codes [/events/{eventId}/analytics]
### List of analytics codes [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array[Analytics code response])

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Add analytics code [POST]
+ Request (application/json)
    + Attributes (Analytics code request)

+ Response 200 (application/json)
    + Attributes (Analytics code response)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Delete analytics code [DELETE]
+ Request (application/json)
    + Attributes (object)
        + `codeId` (string)

+ Response 204 (application/json)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Statistics of event [/events/{eventId}/statistics]
### Statistics [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (object)
        + `discounts` (object)
            + `totallyDiscounted` (array)
                + (object)
                    + `currency`: `CZK` (string)
                    + `amount`: 100 (number)
            + `discounts` (array)
                + (object)
                    + `discountId`: `discount-id` (string)
                    + `name`: `Some discount` (string)
                    + `discount` (array)
                        + (object)
                            + `currency`: `CZK` (string)
                            + `amount`: 100 (number)
                    + `totallyDiscounted` (array)
                        + (object)
                            + `currency`: `CZK` (string)
                            + `amount`: 100 (number)
                    + `amount`: 100 (number)
                    + `remaining`: 90 (number)
                    + `tickets` (array)
                        + (object)
                            + `ticketId`: `ticket-id` (string)
                            + `variantName`: `variant name` (string)
                            + `orderId`: `order-id` (string)
                            + `firstName`: `first name` (string)
                            + `lastName`: `last name` (string)
                            + `orderedAt`: `datetime` (string)
        + `tickets` (array)
            + (object)
                + `variants` (array)
                    + (object)
                        + `ticketVariantId`: `variant-id` (string)
                        + `name`: `visitor` (string)
                        + `fullPrice`: 10 (number)
                        + `discounted`: 10 (number)
                        + `free`: 10 (number)
                        + `guests`: 10 (number)
                        + `unpaid`: 10 (number)
                        + `remaining`: 10 (number)
                + `cumulative` (object)
                    + `monthly` (array)
                        + (object)
                            + `month`: 7 (number)
                            + `year`: 2017 (number)
                            + `variants` (array)
                                + (object)
                                    + `ticketVariantId`: `variant-id` (string)
                                    + `name`: `visitor` (string)
                                    + `total`: 50 (number)
                                    + `fullPrice`: 10 (number)
                                    + `discounted`: 10 (number)
                                    + `free`: 10 (number)
                                    + `guests`: 10 (number)
                                    + `unpaid`: 10 (number)
                    + `daily` (array)
                        + (object)
                            + `day`: 10 (number)
                            + `month`: 7 (number)
                            + `year`: 2017 (number)
                            + `variants` (array)
                                + (object)
                                    + `ticketVariantId`: `variant-id` (string)
                                    + `name`: `visitor` (string)
                                    + `total`: 50 (number)
                                    + `fullPrice`: 10 (number)
                                    + `discounted`: 10 (number)
                                    + `free`: 10 (number)
                                    + `guests`: 10 (number)
                                    + `unpaid`: 10 (number)
                + `separate` (object)
                    + `monthly` (array)
                        + (object)
                            + `month`: 7 (number)
                            + `year`: 2017 (number)
                            + `variants` (array)
                                + (object)
                                    + `ticketVariantId`: `variant-id` (string)
                                    + `name`: `visitor` (string)
                                    + `total`: 50 (number)
                                    + `fullPrice`: 10 (number)
                                    + `discounted`: 10 (number)
                                    + `free`: 10 (number)
                                    + `guests`: 10 (number)
                                    + `unpaid`: 10 (number)
                    + `daily` (array)
                        + (object)
                            + `day`: 10 (number)
                            + `month`: 7 (number)
                            + `year`: 2017 (number)
                            + `variants` (array)
                                + (object)
                                    + `ticketVariantId`: `variant-id` (string)
                                    + `name`: `visitor` (string)
                                    + `total`: 50 (number)
                                    + `fullPrice`: 10 (number)
                                    + `discounted`: 10 (number)
                                    + `free`: 10 (number)
                                    + `guests`: 10 (number)
                                    + `unpaid`: 10 (number)
        + `revenues` (object)
            + `cumulative` (object)
                + `monthly` (array)
                    + (object)
                        + `month`: 7 (number)
                        + `year`: 2017 (number)
                        + `revenue` (array)
                            + (object)
                                + `currency`: `CZK` (string)
                                + `amount`: 123 (number)
                + `daily` (array)
                    + (object)
                        + `day`: 10 (number)
                        + `month`: 7 (number)
                        + `year`: 2017 (number)
                        + `revenue` (array)
                            + (object)
                                + `currency`: `CZK` (string)
                                + `amount`: 123 (number)
            + `separate` (object)
                + `monthly` (array)
                    + (object)
                        + `month`: 7 (number)
                        + `year`: 2017 (number)
                        + `revenue` (array)
                            + (object)
                                + `currency`: `CZK` (string)
                                + `amount`: 123 (number)
                + `daily` (array)
                    + (object)
                        + `day`: 10 (number)
                        + `month`: 7 (number)
                        + `year`: 2017 (number)
                        + `revenue` (array)
                            + (object)
                                + `currency`: `CZK` (string)
                                + `amount`: 123 (number)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

+ Response 404 (application/json)
    + Attributes (404 Error response)


## Ticket input [/ticket-inputs/{inputId}]
### Ticket input detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Ticket input response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit ticket input [PUT]
+ Request (application/json)
    + Attributes (Ticket input request)

+ Response 200 (application/json)
    + Attributes (Ticket input response)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)    

## Cancel ticket input [/ticket-inputs/cancel]
### Cancel ticket input [POST]
+ Request (application/json)
    + Attributes
        + `inputId` (string, required)

+ Response 200 (application/json)
    + Attributes (Ticket input response)
    
+ Response 400 (application/json)
    + Attributes (401 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Export orders [/events/{eventId}/export/orders]
### Get file content [POST]
+ Request (application/json)
    + Attributes (Export content type)
    
+ Response 201 (text/csv)
+ Response 201 (application/vnd.ms-excel)
+ Response 201 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

## Export ticket variants [/events/{eventId}/export/ticket-variants]
### Get file content [POST]
+ Request (application/json)
    + Attributes (Export content type)
    
+ Response 201 (text/csv)
+ Response 201 (application/vnd.ms-excel)
+ Response 201 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

## Export tickets [/events/{eventId}/export/tickets]
### Get file content [POST]
+ Request (application/json)
    + Attributes (Export content type)
    
+ Response 201 (text/csv)
+ Response 201 (application/vnd.ms-excel)
+ Response 201 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

## Export discounts [/events/{eventId}/export/discounts]
### Get file content [POST]
+ Request (application/json)
    + Attributes (Export content type)
    
+ Response 201 (text/csv)
+ Response 201 (application/vnd.ms-excel)
+ Response 201 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

## Export statistics [/events/{eventId}/export/statistics]
### Get file content [POST]
+ Request (application/json)
    + Attributes (Export content type)
    
+ Response 201 (text/csv)
+ Response 201 (application/vnd.ms-excel)
+ Response 201 (application/pdf)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 403 (application/json)
    + Attributes (403 Error response)

## Analytics code [/analytics/{codeId}]
### Analytics code detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Analytics code response)
        + `eventId`

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit analytics code [PUT]
+ Request (application/json)
    + Attributes (Analytics code request)

+ Response 200 (application/json)
    + Attributes (Analytics code response)
        + `eventId`
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

# Data Structures
## Licence type (object)
+ `id`: `962754c0-1201-4cd5-812f-ef616a442445` (string, required)
+ `name`: `Basic` (string, required)

## Licence type with details (Licence type)
+ `prices` (array[Price], required)

## Currency (object)
+ `code`: `CZK` (string, required)
+ `local`: `Kč` (string, required)

## Country (object)
+ `code`: `CZ` (string, required)
+ `name`: `Česká Republika` (string, required)
+ `internationalName`: `Czech Republic` (string, required)
+ `phoneCode`: `+420` (string, required)

## Price (object)
+ `amount`: `100` (number, required)
+ `currency`: `CZK` (string, required)

## Price with discount (object)
+ `originalAmount`: `200` (number)
+ `amount`: `100` (number)
+ `currency`: `CZK` (string)
+ `discount` (object)
    + `id` (string)
    + `code`: `xyz`
    + `name`: `Some discount name`
    + `amount`: `100` (number)

## Licence (object)
+ `validUntil`: `2018-01-01 23:00:00` (string, required)
+ `type` (Licence type, required)

## Licence with id (object)
+ `id`: `a12b0231-be48-4d40-a69d-d521c159dae9` (string, required)
+ Include Licence

## User without email (object)
+ `firstName`: John (string, required)
+ `lastName`: Doe (string, required)
+ `currency`: EUR (string, required)

## User (object)
+ `email`: info@odbav.to (string, required)
+ Include User without email

## User with id (object)
+ `id`: `05f5b1a5-38be-4190-90cd-c084806e45e5` (string, required)
+ Include User

## User with customer (User with id)
+ `showTutorial`: true (boolean)
+ `betaTester:` true (boolean)
+ `customer` (Customer with licence, required)

## Customer (object)
+ `name`: Odbav.to (string, required)
+ include Billing info

## Customer with id (object)
+ `id`: `aa32a9d3-9aaf-4b73-96ff-6da9cbdc8141` (string, required)
+ Include Customer

## Customer with licence (Customer with id)
+ `licence` (Licence with id, required)

## Company (object)
+ `subjectId`: `28994124` (string, required)
+ `subjectVatId`: `CZ12345678` (string, required)
+ `subject`: `Velveth International Corporation s.r.o.` (string, required)
+ `street`: `Slezská 1669/58` (string, required)
+ `city`: `Praha` (string, required)
+ `postalCode`: `12000` (string, required)
+ `countryCode`: `CZ` (string, required)

## Billing info (object)
+ `subject`: `Odbav.to` (string, required)
+ `subjectId`: `12345` (string, required)
+ `subjectVatId`: `CZ12345` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)
+ `accountNumber`: `233432765` (string, required)
+ `bankCode`: `0600` (string, required)
+ `iban`: `CZ6508000000192000145399` (string, required)
+ `bic`: `SWIFTBIC` (string, required)

## Guest credentials (object)
+ `email`: info@odbav.to (string, required)
+ `firstName`: John (string, required)
+ `lastName`: Doe (string, required)

## Guest (Guest credentials)
+ `phone`: `+420123123123` (string, required)
+ `companyName`: `Odbav.to` (string, required)
+ `companyId`: `12345` (string, required)
+ `companyVatId`: `CZ12345` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)

## Ticket editation (object)
+ `price` (Price)
+ `guest` (Guest, required)

## Ticket response (object)
+ `id`: `86cc42db-b22e-4005-99eb-6faf03b41aea` (string)
+ `code`: `c084806e45e5` (string)
+ `status`: `checkedIn` (string)
+ `guest` (Guest credentials)
+ `variantName`: `Some ticket variant` (string)
+ `canBeCheckedIn`: true (boolean)
+ `canBeCheckedOut`: true (boolean)
+ `canBeCancelled`: true (boolean)
+ `canBeEdited`: true (boolean)
+ Include Cancelled

## Ticket detail (Ticket response)
+ `price` (Price with discount)
+ `guest` (Guest)
+ `inputs` (Custom input value)
+ `variant` (object)
    + `id`: `abc-xyz` (string)
    + `name`: `Ticket variant name` (string)
+ `variantName` (optional, nullable)

## Group Ticket detail (object)
+ `groupTicketVariantId`: `5f470e02-3442-488a-9c2c-804e16520e44` (string)
+ `subTickets` (array[Ticket detail])

## Event day (object)
+ `start`: `2017-03-01 08:00:00` (string, required)
+ `end`: `2017-03-01 20:00:00` (string, required)

## Event day 2 (object)
+ `start`: `2017-03-02 06:00:00` (string, required)
+ `end`: `2017-03-02 15:00:00` (string, required) 

## Event bounds (object)
+ `north`: `49.209889999` (number, required)
+ `east`: `16.603493699999945` (number, required)
+ `south`: `49.2098176` (number, required)
+ `west`: `16.603102900000067` (number, required)

## Event location (object)
+ `fullAddress`: `Some random address` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)
+ `lat`: `49.2098` (number, required)
+ `lng`: `16.603` (number, required)
+ `bounds` (Event bounds, required)

## SubEvent body (object)
+ `name`: `Some awesome event!`(string, required)
+ `placeName`: `Event venue`(string, required)
+ `location` (Event location, required)
+ `days` (array[Event day, Event day 2], required)
+ `checkInStartLimited`: `true` (boolean, required)
+ `checkInStartsAt`: `2017-06-06T16:00:00+0100` (string, nullable, required)
+ `description`: `Neat description` (string, required)
+ `timeZone`: `Europe/Prague` (string, optional, nullable)
+ `cancellationPeriod`: 3 (number, nullable, optional)

## Event body (object)
+ Include SubEvent body
+ `organizer`: `ABC promoting ltd` (string, required)
+ `email`: `info@odbav.to` (string, required)
+ `phone`: `+420603123123` (string, required)
+ `link`: `http://odbav.to/tickets/events` (string, required)

## Event id (object)
+ `id`: `acd2d642-3a72-49ef-9c1b-6b248715f8ce` (string, required)

## Event (object)
+ Include Event body

## Event with id (object)
+ Include Event id
+ `formUrl` (nullable)
+ Include Event body
+ `locales` (array)
    + `cs`
    + `en`
+ `checklist` (Event checklist, required)
+ `status`: `ongoing` (string, required)
+ `discountsEnabled`: true (boolean)
+ `analytics` (array[Analytics code response])
+ `canBeEdited`: true (boolean)
+ Include Cancelled

## Event with id and variants (Event with id)
+ `variants` (array[Ticket variant detail symplified], required)
+ `statistics` (object)
    + `paidOrders`: 10 (number)
    + `unpaidOrders`: 10 (number)
    + `cancelledOrders`: 10 (number)
    + `guests`: 10 (number)

## Event terms (object)
+ `useCustomTerms`: true (boolean, required)
+ `terms`: `<html> Terms & conditions </html>` (string, required)

## Order ticket (array)
+ `5f470e02-3442-488a-9c2c-804e16520e44` (string, required)
+ `5fa7b432-3222-4aaa-942c-80fd5c0e4421` (string, required)

## Order ticket detailed (object)
+ `ticketVariantId`: `5f470e02-3442-488a-9c2c-804e16520e44` (string)
+ `email`: `info@odbav.to` (string, optional, nullable)
+ `firstName`: `John` (string, optional, nullable)
+ `lastName`: `Doe` (string, optional, nullable)
+ `phone`: `+420123123123` (string, optional, nullable)
+ `companyName` (string, optional, nullable)
+ `companyId` (string, optional, nullable)
+ `companyVatId` (string, optional, nullable)
+ `street` (string, optional, nullable)
+ `city` (string, optional, nullable)
+ `countryCode` (string, optional, nullable)
+ `postalCode` (string, optional, nullable)

## Order Group ticket (object)
+ `groupTicketVariantId`: `5f470e02-3442-488a-9c2c-804e16520e44` (string)
+ `subTickets` (Order ticket, required)

## Order Group ticket detailed (object)
+ `groupTicketVariantId`: `5f470e02-3442-488a-9c2c-804e16520e44` (string)
+ `subTickets` (array[Order ticket detailed], required)

## Custom input request (object)
+ `inputId`: `1` (string)
+ `value`: `Some value` (string)

## Custom input value (array)
+ (Custom input request)
    + `label`: `Some label` (string)

## Custom input response (array)
+ (object)
    + `id`: `1` (string)
    + `label`: `Firma kterou zastupujete` (string)
    + `type`: `text` (string)
    + `required`: true (boolean)
    + `minLength`: 2 (nullable, number)
    + `maxLength`: 4 (nullable, number)
+ (object)
    + `id`: `2` (string)
    + `label`: `Pozice ve firmě` (string)
    + `type`: `select` (string)
    + `required`: false (boolean)
    + `minLength`: 2 (nullable, number)
    + `maxLength`: 4 (nullable, number)
    + `choices` (array)
        + `a`
        + `b`

## Order request (object)
+ `customer` (Guest)
+ `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, optional)
+ `currency`: `CZK` (string, required)
+ `discountCode` (string, optional, nullable)
+ `status` (string, optional, nullable)

## Order response (object)
+ `id`: `7c9a8379-8fba-48d9-b5b6-146b4083e01f` (string)
+ `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string)
+ `status`: `created` (string)
+ `price` (Price with discount)
+ `customer` (Guest credentials)
+ Include Cancelled
+ `payment` (Bank transfer payment)
+ `ticketsCount`: 1 (number)
+ `groupTickets` (array[Group Ticket detail])
+ `canBeMarkedAsPaid`: false (boolean)
+ `canBeDeleted`: false (boolean)
+ `canBeEdited`: false (boolean)
+ `ticketsCanBeSent`: false (boolean)
+ `invoiceCanBeSent`: false (boolean)
+ `ticketsCanBeDownloaded`: true (boolean)

## Order detail (Order response)
+ `customer` (Guest)
+ `tickets` (array[Ticket detail], required)

## Ticket variant body (object)
+ `name`: `Some ticket variant` (string, required)
+ `internalName`: `internal name of ticket variant` (string, required)
+ `prices` (array[Price], required)
+ `amount`: `1000` (number, required)
+ `amountLimited`: `true` (boolean, required)
+ `checkInStartLimited`: `true` (boolean, required)
+ `checkInStartsAt`: `2017-06-06T16:00:00+0100` (string, nullable, required)
+ `useEventCheckInLimitation`: `true` (boolean, required)
+ `public`: `true` (boolean, required)

## Single ticket variant body (object)
+ `type`: `single` (enum[string])
    + Members
        + `single`
        + `group`
+ `description`: `description of ticket variant` (string, required)
+ `img`: `05f5b1a5-38be-4190-90cd-c084806e4555` (string, required)
+ Include Ticket variant body

## Group ticket variant body (object)
+ `type`: `group` (enum[string])
    + Members
        + `single`
        + `group`
+ Include Ticket variant body
+ `subtickets` (array)
    + (object)
        + `id`: `id-of-subticket-to-edit` (string)
        + `name`: `Some ticket variant` (string, required)
        + `internalName`: `internal name of ticket variant` (string, required)
        + `description`: `Some description of the ticket variant` (string, required)
        + `img`: `05f5b1a5-38be-4190-90cd-c084806e4555` (string, required)

## Ticket variant detail symplified (object)
+ `id`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)
+ Include Single ticket variant body
+ `sold`: `23` (number, required)
+ `remaining`: `15` (number, required)
+ Include Cancelled

## Single ticket variant detail (object)
+ `type`: `single` (enum[string])
    + Members
        + `single`
        + `group`
+ Include Ticket variant detail symplified
+ `currencies` (array)
    + `EUR`
    + `CZK`
+ `inputsEnabled`: true (boolean)
+ `inputs` (Custom input response)

## Group ticket variant detail (object)
+ `id`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)
+ `type`: `group` (enum[string])
    + Members
        + `single`
        + `group`
+ Include Ticket variant body
+ `subtickets` (array)
    + (object)
        + `id`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)
        + `name`: `Some ticket variant` (string, required)
        + `internalName`: `internal name of ticket variant` (string, required)
        + `description`: `Some description of the ticket variant` (string, required)
        + `img`: `05f5b1a5-38be-4190-90cd-c084806e4555` (string, required)
        + `inputsEnabled`: true (boolean)
        + `inputs` (Custom input response)
+ `sold`: `23` (number, required)
+ `remaining`: `15` (number, required)
+ Include Cancelled


## Form type (object)
+ `type`: `input` (string, required)
+ `fieldName`: `lorem ipsum` (string, required)
+ `type`: `text` (string, required)
+ `toggled`: `false` (boolean, required)

## Event checklist (object)
+ `isReady`: false (boolean, required)
+ `ticketVariant`: false (boolean, required)
+ `location`: false (boolean, required)
+ `date`: false (boolean, required)
+ `billingInfo`: false (boolean, required)

## Error (object)
+ `title`: `Short title of the problem`
+ `detail`: `I guess something went wrong, description of error goes here`
+ `code`: `ERROR_123_PHONE_FORMAT` (string)

## 400 Error (Error)
+ source (object)
    + `pointer`
    + `parameter`

## 400 Error response (object)
+ errors (array[400 Error, 400 Error])

## 401 Error response (object)
+ errors (array[Error])

## 403 Error response (object)
+ errors (array[Error])

## 404 Error response (object)
+ errors (array[Error])

## Cancelled (object)
+ `cancelled`
    + `user`: `ca529a7e-d65b-4e6b-a120-eeccc71a1516` (string)
    + `date`: `2017-06-06T16:00:00+0100` (string)

## Bank transfer payment (object)
+ `bankName`: `Fio Banka, a.s.`
+ `variableSymbol`: `123456789`
+ `accountNumber`: `1234567/2010`
+ `iban`: `12312312313`
+ `bic`: `CZ123121313`

## Discount body (object)
+ `name`: `Discount for students` (string, required)
+ `internalName`: `Student` (string, required)
+ `amountLimited`: true (boolean, required)
+ `amount`: 20 (number, required)
+ `code`: `XYZ` (string, required)
+ `validSince`: `2017-06-06T16:00:00+0100` (string, required)
+ `validUntil`: `2018-06-06T16:00:00+0100` (string, required)
+ `discounts` (array):
    + (object)
        + `amount`: 100 (number, required)
        + `currency`: `CZK` (string, required)

## Discount request (object)
+ Include Discount body
+ `ticketVariants` (array[string])
    + `12345`

## Discount response (object)
+ `id` (string)
+ Include Discount body
+ `used`: 5 (number)
+ `remaining`: 10 (number)
+ `ticketVariants` (array):
    + (object)
        + `ticketVariantId`: `12345` (string)
        + `name`: `Variant name` (string)
        + `internalName`: `Variant internal name` (string)

## Ticket input body (object)
+ `type` (enum[string])
    + Members
        + `text`
        + `longText`
        + `select`
        + `checkbox`
        + `radioList`
+ `label`: `What is your name` (string, required)
+ `required`: true (boolean)
+ `choices` (optional, nullable)
+ `minLength`: 2 (optional, nullable, number)
+ `maxLength`: 4 (optional, nullable, number)
+ `guestField` (enum[string], nullable, optional)
    + Members
        + `firstName`
        + `lastName`
        + `email`
        + `phone`
        + `companyName`
        + `companyId`
        + `companyVatId`
        + `street`
        + `city`
        + `countryCode`
        + `postalCode`
+ `validation` (enum[string], nullable, optional)
    + Members
        + `email`
        + `phone`
        + `url`
        + `countryCode`

## Export content type (object)
+ `contentType` (enum[string])
    + Members
        + `application/vnd.ms-excel`
        + `application/pdf`
        + `text/csv`

## Analytics code request (object)
+ `name` (string, required
+ `type` (enum[string], required)
    + Members
        + `facebook-pixel`
        + `seznam-retargeting`
        + `google-analytics`
        + `google-ads`
+ `code` (string, required)

## Analytics code response (object)
+ `id`: `1c1177e8-5b1a-11e7-907b-a6006ad3dba0` (string)
+ Include Analytics code request

## Ticket input request (object)
+ Include Ticket input body
+ `ticketVariants` (array[string])
    + `1c11711c-5b1a-11e7-907b-a6006ad3dba0`

## Ticket input response (object)
+ `id`: `1c1177e8-5b1a-11e7-907b-a6006ad3dba0` (string)
+ Include Ticket input body
+ `ticketVariants` (array):
    + (object)
        + `ticketVariantId`: `1c11711c-5b1a-11e7-907b-a6006ad3dba0` (string)
        + `name`: `Variant name` (string)
        + `internalName`: `Variant internal name` (string)
+ Include Cancelled