FORMAT: 1A

# Odbav.to

<!--
## Translations [/translations]
### List of all translations [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Translation)

+ Response 401 (application/json)
    + Attributes (401 Error response)
-->


## Licence types [/licence-types]
### List of all licence types [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Licence type with details)

## Currencies [/currencies]
### List of supported currencies [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Currency)

## Countries [/countries]
### List of supported countries [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Country)
            + `currency`: `CZK`

## Logged user [/me]
### Retrieve informations about itself [GET]
+ Request (application/json)
        
+ Response 200 (application/json)
    + Attributes (User with customer)

+ Response 401 (application/json)
    + Attributes (401 Error response)


### Update user details [PUT]
+ Request (application/json)
    + Attributes (User without email)
            
+ Response 200 (application/json)
    + Attributes (User with customer)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Users [/users]
### List all users of same customer [GET]
+ Request (application/json)

+ Response 200 (appication/json)
    + Attributes (array)
        + (User with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)

### Add new user to a customer [POST]
+ Request (application/json)
    + Attributes (User)
        + `password` (nullable) - password will be generated automatically if null

+ Response 201 (application/json)
    + Attributes (User with id)
            
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Check in [/check-in]
### Check code for check in [POST]
+ Request (application/json)
    + Attributes (object)
        + `code`: `c084806e45e5` (string, required)

+ Response 201 (application/json)
    + Attributes (Ticket with id)

+ Response 400 (application/json)
    + Attributes
        + `ticket` (Ticket with id)
        + Include 400 Error response

+ Response 401 (application/json)
    + Attributes (401 Error response)


## Check out [/check-out]
### Check code for check out [POST]
+ Request (application/json)
    + Attributes (object)
        + `code`: `c084806e45e5` (string, required)

+ Response 201 (application/json)
    + Attributes (Ticket with id)

+ Response 400 (application/json)
    + Attributes
        + `ticket` (Ticket with id)
        + Include 400 Error response

+ Response 401 (application/json)
    + Attributes (401 Error response)


## Events [/events]
### List events [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Event with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)

### Create new event [POST]
+ Request (application/json)
    + Attributes (Event)

+ Response 201 (application/json)
    + Attributes (Event with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)

## Cancel event [/events/cancel]
### Cancel event [POST]
+ Request (application/json)
    + Attributes (object)
        + `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Event detail [/events/{eventId}]
### Event detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Event with id and variants)
        
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit event details [PUT]
+ Request (application/json)
    + Attributes (Event body)

+ Response 200 (application/json)
    + Attributes (Event with id)
        
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Ticket variants [/events/{eventId}/ticket-variants]
### List event ticket variants [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Ticket variant with id and currencies)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create new ticket variant [POST]
+ Request (application/json)
    + Attributes (Ticket variant)

+ Response 201 (application/json)
    + Attributes (Ticket variant with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel ticket variant [/ticket-variants/cancel]
### Cancel ticket variant [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketVariantId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Ticket variant detail [/ticket-variants/{ticketVariantId}]
### Ticket variant detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Ticket variant with id and currencies)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit ticket variant [PUT]
+ Request (application/json)
    + Attributes (Ticket variant)

+ Response 200 (application/json)
    + Attributes (Ticket variant with id and currencies)
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Tickets [/events/{eventId}/tickets]
### List event tickets [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Ticket with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)

+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create new ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `variantId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`
        + `guest` (Guest)

+ Response 201 (application/json)
    + Attributes (Ticket with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel ticket [/tickets/cancel]
### Cancel ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Ticket detail [/tickets/{ticketId}]
### Ticket detail [GET]
+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (Ticket with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit ticket [PUT]
+ Request (application/json)
    + Attributes (Ticket editation)
        
+ Response 200 (application/json)
    + Attributes (Ticket with id)

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Tickets sending [/tickets/send]
### Send ticket [POST]
+ Request (application/json)
    + Attributes (object)
        + `ticketId` (string, required)
        + `email` (string, required) - Email to which deliver the ticket

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Orders [/orders]
### List orders [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Order with id)
            + `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Create order (customer from outside) [POST]
+ Request (application/json)
    + Attributes (Order)
        + `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658`
        + `currency`: `CZK`
        + `tickets` (Order ticket)

+ Response 201 (application/json)
    + Attributes (Order with id)
    <!-- + Attributes (Order with id and ticket variant info) -->

+ Response 400 (application/json)
    + Attributes (400 Error response)
    

## Event orders [/events/{eventId}/orders]
### List event orders [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Order with id)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

### Create order (manual or cashdesk) [POST]
+ Request (application/json)
    + Attributes (Order)
        + `status`: `paidByCash`
        + `currency`: `CZK`
        + `tickets` (Order ticket)

+ Response 201 (application/json)
    + Attributes (Order with id)
    <!-- + Attributes (Order with id and ticket variant info) -->

+ Response 400 (application/json)
    + Attributes (400 Error response)
    
+ Response 401 (application/json)
    + Attributes (400 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    

## Cancel order [/orders/cancel]
### Cancel order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string)

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Invoices sending [/orders/send-invoice]
### Send invoice for order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string, required)
        + `email` (string, required) - Email to which deliver the invoice

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Order tickets sending [/orders/send-tickets]
### Send all tickets belonging to order [POST]
+ Request (application/json)
    + Attributes (object)
        + `orderId` (string, required)
        + `email` (string, required) - Email to which deliver the tickets

+ Response 204 (application/json)
    
+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 403 (application/json)
    + Attributes (403 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Order detail [/orders/{orderId}]
### Order detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Order with id and ticket variant info)

+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit order [PUT]
+ Request (application/json)
    + Attributes (Guest)

+ Response 200 (application/json)
    + Attributes (Order with id and ticket variant info)
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Pay order [/orders/{orderId}/card-pay]
### Create transaction and redirect [POST]
+ Request (application/json)
    + Attributes
        + `successReturnUrl`: `http://odbav.to/some-success-url` (string, required) - Url where user will be returned on successful payment
        + `failureReturnUrl`: `http://odbav.to/some-failure-url` (string, required) - Url where user will be returned on failed payment

+ Response 302 (application/json)

+ Response 400 (application/json)
    + Attributes (400 Error response)

## Company info [/company-info/{companyId}]
### Retrieve info from public registry [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Company)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

## Billing detail [/billing]
### Billing detail [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Billing info)
        + `customerId`: `5f470e02-3442-488a-9c2c-804e16520e44`

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)

### Edit billing [PUT]
+ Request (application/json)
    + Attributes (Billing info)

+ Response 200 (application/json)
    + Attributes (Billing info)
        + `customerId`: `5f470e02-3442-488a-9c2c-804e16520e44`
        
+ Response 400 (application/json)
    + Attributes (400 Error response)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


## Statistics payments [/events/{eventId}/statistics/payments]
### Get payments [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Statistics payment)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)
    
    

## Statistics tickets [/events/{eventId}/statistics/tickets]
### Get tickets [GET]
+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (array)
        + (Statistics ticket)

+ Response 401 (application/json)
    + Attributes (401 Error response)
    
+ Response 404 (application/json)
    + Attributes (404 Error response)


# Data Structures
## Licence type (object)
+ `id`: `962754c0-1201-4cd5-812f-ef616a442445` (string, required)
+ `name`: `Basic` (string, required)

## Licence type with details (Licence type)
+ `prices` (array[Price], required)

## Currency (object)
+ `code`: `CZK` (string, required)
+ `local`: `Kč` (string, required)

## Country (object)
+ `code`: `CZ` (string, required)
+ `name`: `Česká Republika` (string, required)
+ `internationalName`: `Czech Republic` (string, required)
+ `phoneCode`: `+420` (string, required)

## Price (object)
+ `amount`: `100` (number, required)
+ `currency`: `CZK` (string, required)

## Price 2 (object)
+ `amount`: `4` (number, required)
+ `currency`: `EUR` (string, required)

## Licence (object)
+ `validUntil`: `2018-01-01 23:00:00` (string, required)
+ `type` (Licence type, required)

## Licence with id (object)
+ `id`: `a12b0231-be48-4d40-a69d-d521c159dae9` (string, required)
+ Include Licence

## User without email (object)
+ `firstName`: John (string, required)
+ `lastName`: Doe (string, required)
+ `currency`: EUR (string, required)

## User (object)
+ `email`: info@odbav.to (string, required)
+ Include User without email

## User with id (object)
+ `id`: `05f5b1a5-38be-4190-90cd-c084806e45e5` (string, required)
+ Include User

## User with customer (User with id)
+ `customer` (Customer with licence, required)

## Customer (object)
+ `name`: Odbav.to (string, required)
+ include Billing info

## Customer with id (object)
+ `id`: `aa32a9d3-9aaf-4b73-96ff-6da9cbdc8141` (string, required)
+ Include Customer

## Customer with licence (Customer with id)
+ `licence` (Licence with id, required)

## Company (object)
+ `subjectId`: `28994124` (string, required)
+ `subjectVatId`: `CZ12345678` (string, required)
+ `subject`: `Velveth International Corporation s.r.o.` (string, required)
+ `street`: `Slezská 1669/58` (string, required)
+ `city`: `Praha` (string, required)
+ `postalCode`: `12000` (string, required)
+ `countryCode`: `CZ` (string, required)

## Billing info (object)
+ `subject`: `Odbav.to` (string, required)
+ `subjectId`: `12345` (string, required)
+ `subjectVatId`: `CZ12345` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)
+ `accountNumber`: `233432765` (string, required)
+ `bankCode`: `0600` (string, required)
+ `iban`: `CZ6508000000192000145399` (string, required)
+ `bic`: `SWIFTBIC` (string, required)

## Translation (object)
+ `key`: `hello-world` (string, required)
+ `translation`: `Lorem ipsum dolor sit amet` (string, required)

## Guest (object)
+ `email`: info@odbav.to (string, required)
+ `firstName`: John (string, required)
+ `lastName`: Doe (string, required)
+ `phone`: `+420123123123` (string, required)
+ `companyName`: `Odbav.to` (string, required)
+ `companyId`: `12345` (string, required)
+ `companyVatId`: `CZ12345` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)


## Ticket id (object)
+ `id`: `86cc42db-b22e-4005-99eb-6faf03b41aea` (string, required)

## Ticket (object)
+ `code`: `c084806e45e5` (string, required)
+ `price` (Price)
+ `status`: `checkedIn` (string, required)
+ `event`
    + `id`: `6bd945c3-8a3e-4e1a-9fd3-2b6a0291eaba` (string, required)
    + `name`: `Some event` (string, required)
    + `variant`
        + `id`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)
        + `name`: `Some ticket variant` (string, required)
+ `guest` (Guest, required)

## Ticket editation (object)
+ `price` (Price)
+ `guest` (Guest, required)

## Ticket with id (object)
+ Include Ticket id
+ Include Ticket
+ Include Cancelled

## Event day (object)
+ `start`: `2017-03-01 08:00:00` (string, required)
+ `end`: `2017-03-01 20:00:00` (string, required)

## Event day 2 (object)
+ `start`: `2017-03-02 06:00:00` (string, required)
+ `end`: `2017-03-02 15:00:00` (string, required) 

## Event bounds (object)
+ `north`: `49.209889999` (number, required)
+ `east`: `16.603493699999945` (number, required)
+ `south`: `49.2098176` (number, required)
+ `west`: `16.603102900000067` (number, required)

## Event location (object)
+ `fullAddress`: `Some random address` (string, required)
+ `street`: `Anonymous 123` (string, required)
+ `city`: `Prague` (string, required)
+ `countryCode`: `CZ` (string, required)
+ `postalCode`: `11000` (string, required)
+ `lat`: `49.2098` (number, required)
+ `lng`: `16.603` (number, required)
+ `bounds` (Event bounds, required)

## Event body (object)
+ `name`: `Some awesome event!`(string, required)
+ `placeName`: `Event venue`(string, required)
+ `location` (Event location, required)
+ `days` (array[Event day, Event day 2], required)
+ `organizer`: `ABC promoting ltd` (string, required)
+ `description`: `Neat description` (string, required)
+ `email`: `info@odbav.to` (string, required)
+ `phone`: `+420603123123` (string, required)
+ `link`: `http://odbav.to/tickets/events` (string, required)


## Event id (object)
+ `id`: `acd2d642-3a72-49ef-9c1b-6b248715f8ce` (string, required)

## Event with variants (object)
+ Include Event body
+ `variants` (array[Ticket variant], required)

## Event (object)
+ Include Event body

## Event with id (object)
+ Include Event id
+ Include Event body
+ `checklist` (Event checklist, required)
+ Include Cancelled

## Event with id and variants (Event with id)
+ `variants` (array[Ticket variant with id], required)

## Order ticket (array)
+ `5f470e02-3442-488a-9c2c-804e16520e44` (string, required)
+ `5fa7b432-3222-4aaa-942c-80fd5c0e4421` (string, required)

## Order ticket with event info (object)
+ Include Ticket id
+ `code`: `c084806e45e5` (string, required)
+ `price` (Price, required)
+ `variant`
    + `id`: `5f470e02-3442-488a-9c2c-804e16520e44` (string, required)
    + `name`: `Some variant name` (string, required)
    + `event`
        + Include Event id
        + `name`: `Some event name` (string, required)

## Order (object)
+ `customer` (Guest, required)

## Order with id (object)
+ `id`: `7c9a8379-8fba-48d9-b5b6-146b4083e01f` (string, required)
+ `eventId`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)
+ `status`: `created` (string, required)
+ `price` (Price, required)
+ Include Order
+ Include Cancelled

## Order with id and ticket variant info
+ Include Order with id
+ `tickets` (array[Order ticket with event info], required)

## Ticket variant (object)
+ `name`: `Some ticket variant` (string, required)
+ `internalName`: `internal name of ticket variant` (string, required)
+ `prices` (array[Price, Price 2], required)
+ `amount`: `1000` (number, required)
+ `amountLimited`: `true` (boolean, required)
+ `public`: `true` (boolean, required)
+ `img`: `05f5b1a5-38be-4190-90cd-c084806e4555` (string, required)

## Ticket variant id (object)
+ `id`: `fed4cb08-2a18-446e-b549-d9e0f768f658` (string, required)

## Ticket variant with id (object)
+ Include Ticket variant id
+ Include Ticket variant
+ Include Cancelled
+ `sold`: `23` (number, required)
+ `remaining`: `15` (number, required)

## Ticket variant with id and currencies (object)
+ Include Ticket variant id
+ Include Ticket variant
+ `currencies` (array, required)
    + `EUR`
    + `CZK`

## Statistics cashbook (object)
+ `datetime`: `2017-03-02 06:00:00` (string, required)
+ `price` (Price, required)
+ `cashdeskId`: `1` (string, required)

## Statistics payment (object)
+ `paymentDate`: `2017-03-02 06:00:00` (string, required)
+ `paymentType`: `card` (string, required)
+ `paymentNo`: `1(P2)160002402` (string, required)
+ `priceTotalCZK`: `100` (number, required)
+ `priceNoVatCZK`: `85` (number, required)
+ `priceVatCZK`: `15` (number, required)
+ `priceInclVatCZK`: `100` (number, required)
+ `priceInclVatEUR`: `4` (number, required)

## Statistics ticket (object)
+ `paymentDate`: `2017-03-02 06:00:00` (string, required)
+ `paymentType`: `card` (string, required)
+ `paymentNo`: `1(P2)160002402` (string, required)
+ `ticketNo`: `178718815296` (string, required)
+ `priceTotalCZK`: `100` (number, required)
+ `priceNoVatCZK`: `85` (number, required)
+ `priceVatCZK`: `15` (number, required)
+ `priceInclVatCZK`: `100` (number, required)
+ `priceInclVatEUR`: `4` (number, required)

## Form type (object)
+ `type`: `input` (string, required)
+ `fieldName: `lorem ipsum` (string, required)
+ `type`: `text` (string, required)
+ `toggled`: `false` (boolean, required)

## Event checklist (object)
+ `isReady`: false (boolean, required)
+ `ticketVariant`: false (boolean, required)
+ `location`: false (boolean, required)
+ `date`: false (boolean, required)
+ `billingInfo`: false (boolean, required)

## Error (object)
+ `title`: `Short title of the problem`
+ `detail`: `I guess something went wrong, description of error goes here`

## 400 Error (Error)
+ source (object)
    + `pointer`
    + `parameter`

## 400 Error response (object)
+ errors (array[400 Error, 400 Error])

## 401 Error response (object)
+ errors (array[Error])

## 403 Error response (object)
+ errors (array[Error])

## 404 Error response (object)
+ errors (array[Error])

## Cancelled (object)
+ `cancelled`
    + `user`: `ca529a7e-d65b-4e6b-a120-eeccc71a1516` (string)
    + `date`: `2017-06-06 12:00:00` (string)